FROM openkbs/nodejs-nonroot-docker

MAINTAINER DrSnowbird "DrSnowbird@openkbs.org"

USER ${USER}
WORKDIR ${HOME}

#########################
#### ---- Entry ---- ####
#########################
#### (Add your child container code here)
#### (Add your child container code here)
#### (Add your child container code here)

#########################
#### ---- Entry ---- ####
#########################
ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["/bin/bash"]
